import {renderLedgerTable} from './ledger-table.mjs';
import {secretaryLetters} from './secretary-mailbox.mjs';
import {activityGuide} from './activity-guide.mjs';
import {readMailBody} from './ledger.mjs';
const e=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const time=x=>x?new Date(x).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false}):'모름';
export function renderDecisions(items,error,token){
 if(error)return `<section class="panel" id="decisions" data-view="decisions"><h2>내 결정 필요</h2><p role="alert">모름: ${e(error)}</p></section>`;
 const open=items.filter(d=>d.status==='open');
 const one=d=>`<article id="decision-${e(d.id)}"><h3>${e(d.question)}</h3><p><a href="?card=${encodeURIComponent(d.card)}#detail">${e(d.card)}</a> · 요청자 ${e(d.requestedBy)}</p><p><strong>추천: ${e(d.recommendation)}</strong></p><p style="white-space:pre-wrap">${e(d.reason)}</p>${d.status==='open'?`<form method="post" action="/decisions/answer"><input type="hidden" name="token" value="${e(token)}"><input type="hidden" name="id" value="${e(d.id)}"><input type="hidden" name="revision" value="${d.revision}"><label>선택 (선택 사항)<select name="choice"><option value="">직접 답변</option>${d.options.map(o=>`<option value="${e(o)}">${e(o)}</option>`).join('')}</select></label><label>결정 내용<textarea name="text" rows="3"></textarea></label><button>답변 전달</button><p class="muted">선택지만 골라도 답할 수 있습니다. 답변을 저장하고 요청한 슈퍼감독에게 한 번 알립니다.</p></form>`:d.status==='answered'?`<p><strong>답변:</strong> ${e(d.answer.text)}</p><p>통지: ${e(d.delivery?.status==='sent'?'전달됨':d.delivery?.status==='failed'?'실패 — 답변은 저장됨':'확인 필요 — 답변은 저장됨')}</p>`:`<p>취소: ${e(d.cancelReason)}</p>`}</article>`;
 return `<section class="panel" id="decisions" data-view="decisions"><h2>내 결정 필요 ${open.length}건</h2><p class="muted">슈퍼감독이 [kyle]에게 명시적으로 요청한 결정만 표시합니다.</p>${open.map(one).join('<hr>')||'<p>결정을 기다리는 요청이 없습니다.</p>'}<details><summary>이전 결정 ${items.length-open.length}건</summary>${items.filter(d=>d.status!=='open').slice().reverse().map(one).join('<hr>')}</details></section>`;
}
const recordTabs=active=>`<nav class="record-tabs" aria-label="시스템 기록 보기"><a href="#runs" ${active==='runs'?'aria-current="page"':''}>작업별 보기</a><a href="#ledger" ${active==='ledger'?'aria-current="page"':''}>사건순 보기</a></nav>`;
export function renderActivity({center,entries=[],ledgerLines,error,home},url){
 const known=ledgerLines!==null&&!entries.some(e=>e?.broken);
 if(!known)return [['mailbox','우편함'],['runs','작업 실행 기록'],['ledger','시스템 기록']].map(([id,title])=>`<section class="panel" id="${id}" data-view="${id}"><h2>${id==='mailbox'?title:'시스템 기록'}</h2>${id==='mailbox'?'':recordTabs(id)}${activityGuide(id)}<p role="alert">모름 — 원장을 읽을 수 없습니다.</p></section>`).join('');
 const unread=secretaryLetters(entries).filter(e=>!e.read).length;
 const readIds=new Set(entries.filter(e=>e.kind==='mail-read').map(e=>e.mailId));
 const role=url.searchParams.get('mailRole')||'',hideWatch=url.searchParams.get('hideWatch')==='1';
 const all=entries.filter(x=>x.kind==='send'&&(url.searchParams.get('mailUnread')!=='1'||(x.transport==='mailbox'&&x.role==='비서'&&!readIds.has(x.mailId)))&&(!role||x.role===role||x.by===role)&&(!hideWatch||x.by!=='watch')).slice().reverse();
 const paginate=(items,param)=>{const n=Math.max(1,Math.min(Math.ceil(items.length/25)||1,Math.floor(Number(url.searchParams.get(param)))||1));const link=k=>{const q=new URLSearchParams(url.searchParams);q.set(param,k);return '?'+q+'#'+(param==='mailPage'?'mailbox':param==='runPage'?'runs':'ledger')};return{items:items.slice((n-1)*25,n*25),nav:`<nav>${n>1?`<a href="${e(link(n-1))}">이전</a>`:''}<span>${n} / ${Math.ceil(items.length/25)||1}</span>${n*25<items.length?`<a href="${e(link(n+1))}">다음</a>`:''}</nav>`}};
 const mails=paginate(all,'mailPage'),logs=paginate(entries.slice().reverse(),'logPage');
 const runs=[...(center?.cards??[]).flatMap(c=>c.runs.map(r=>({...r,card:c.key,board:c.board}))),...(center?.unregistered??[])];
 const executions=paginate(runs,'runPage');
 return `<section class="panel" id="mailbox" data-view="mailbox"><h2>우편함</h2>${activityGuide('mailbox')}<p><a href="?mailRole=${encodeURIComponent('비서')}#mailbox">비서와 주고받은 공식 우편 · 미확인 ${unread}건</a></p><p class="muted">비서 우편은 저장 후 이 대화에서 확인합니다. 자동 깨움은 연결되지 않았으며 일반 대화는 수집하지 않습니다.</p><p class="muted">실제 발송 기록입니다. 전달 기록은 상대의 처리 완료를 뜻하지 않습니다.</p><form class="toolbar" method="get" action="/#mailbox"><label><input type="checkbox" name="mailUnread" value="1"${url.searchParams.get('mailUnread')==='1'?' checked':''}>비서 미확인만</label><label>발신·수신 역할<input name="mailRole" value="${e(role)}"></label><label><input type="checkbox" name="hideWatch" value="1"${hideWatch?' checked':''}>감시 우편 숨기기</label><button>우편 조회</button></form><div class="scroll"><table><thead><tr><th>시각</th><th>보낸이</th><th>받는이</th><th>내용</th></tr></thead><tbody>${mails.items.map(m=>{let body;try{body=home&&m.digest?readMailBody(m.digest,home):null}catch{body=null}return `<tr><td>${e(time(m.t))}</td><td>${e(m.by||'모름')}</td><td>${e(m.role||'모름')}</td><td>${e(m.taskId||'')}${m.transport==='mailbox'?`<span class="state">${readIds.has(m.mailId)?'비서 확인함':'비서 미확인'} · 저장됨</span><small> ${e(({request:'작업 요청',decision:'결정',report:'공식 보고'})[m.mailKind]||m.mailKind)}</small>`:''}<p>${e(m.preview||(m.transport==='mailbox'?'공식 우편 · 본문을 펼쳐 확인':'미리보기 없음'))}</p><details><summary>본문</summary><pre>${e(body??'본문 없음 또는 읽기 불가 — 원장 기록은 보존됨')}</pre></details></td></tr>`}).join('')}</tbody></table></div>${mails.nav}</section>
 <section class="panel" id="runs" data-view="runs"><h2>시스템 기록</h2>${recordTabs('runs')}<h3>작업별 보기</h3>${activityGuide('runs')}<p class="muted">중앙 카드와 같은 계산을 사용합니다. 세션 생존만으로 진행이라고 표시하지 않습니다.</p><div class="scroll"><table><thead><tr><th>카드</th><th>역할 · 판</th><th>실행 기록</th></tr></thead><tbody>${executions.items.map(r=>`<tr><td>${r.card?`<a href="?card=${encodeURIComponent(r.card)}#detail">${e(r.card)}</a>`:e(r.taskId)}</td><td>${e(r.role)}<br>${e(r.board||'판 미지정')}</td><td>${e(({done:'완료 기록',failed:'실패 기록',unconfirmed:'완료 미확인',orphaned:'세션 없음·미완료'})[r.state]||r.state)}<br>${e(time(r.at))}</td></tr>`).join('')}</tbody></table></div>${executions.nav}</section>
 <section class="panel lg-panel" id="ledger" data-view="ledger"><div class="lg-top"><h2>시스템 기록</h2>${recordTabs('ledger')}</div><div class="lg-heading"><h3>사건순 보기</h3><span>${entries.length}건 · 최신순</span><details class="lg-help"><summary>기록 안내</summary>${activityGuide('ledger')}</details></div><p class="lg-caption">한 줄이 사건 하나입니다. 행을 펼쳐 원문을 확인합니다. 과거 기록과 현재 상태는 구분해서 봅니다.</p>${renderLedgerTable(logs.items)}<div class="lg-pagination">${logs.nav}</div></section>`;
}
